FROM golang:1.22 AS builder

WORKDIR /app
COPY . .

RUN go mod download
RUN CGO_ENABLED=1 GOOS=linux go build -o bmc-sqlite main.go

FROM gcr.io/distroless/base-debian11
WORKDIR /
COPY --from=builder /app/bmc /bmc
COPY --from=builder /app/data /data

ENV USE_SQL=true
EXPOSE 8080
ENTRYPOINT ["/bmc"]
