{{- if .Values.csv.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmc-csv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bmc-csv
  template:
    metadata:
      labels:
        app: bmc-csv
    spec:
      containers:
        - name: bmc-csv
          image: "{{ .Values.csv.image }}:{{ .Values.csv.tag }}"
          ports:
            - containerPort: {{ .Values.csv.port }}
          env:
            - name: USE_SQL
              value: "false"
{{- end }}
